### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by jemarr** [pkoerber/SMA-SunnyBoy-Reader#1]
Hi.

I'm testing your library but I allways got failed connection. Just tested the example with my credentials. I've checked USER and INSTALLER, with same result. With Debug option I got this:

[HTTP] POST... URL: http://192.168.1.5/dyn/login.json
[HTTP] POST... message: {"right":"istl", "pass":"jemaxxxxxxx"}
[HTTP] POST... failed, error: 301: 
Getting values: fail

I've have a Raspberry Pi with Node-Red and the SMA-webconnect node working perfect.

In this Node configuration I must check 'Use HTTPS Connection'....

Could be this the issue ???

When I access the SMA webpage at its iP adress, I need to grand the https access.

I've a SMA Sunny-Boy 4.0

Thanks

**Comment by pkoerber** [comment]
Maybe you have to indeed use https. You can try to replace http with https in the code.  Also possible is that your specific SunnyBoy uses other URLs, i.e. not anymore http://192.168.1.5/dyn/login.json or https://192.168.1.5/dyn/login.json

**Comment by jemarr** [comment]
Would you tell me where (file and line) I must replace 'http' with 'https', please

**Comment by jemarr** [comment]
I've replaced http with https at SMAReader.cpp in all lines like this: "https://%d.%d.%d.%d/dyn/....

Now I got a connection refused error:

[HTTP] POST... URL: https://192.168.1.5/dyn/login.json
[HTTP] POST... message: {"right":"istl", "pass":"jemaxxxxxxx"}
[HTTP] POST... failed, error: -1: connection refused
Getting values: fail
Try: 0

**Comment by pkoerber** [comment]
I think the original error is better (301), but I don't have the answer unfortunately. It's an error that the inverter gives in reply to the http post request. In my case it sometimes also fails, but it works most of the time. You can also try this Python code on your normal computer: https://github.com/Dymerz/SMA-SunnyBoy. I got the details of the SunnyBoy API from there since there is not really a manual from SMA.
